module.exports = {
  'Accounts': '/accounts',
  'Extensions': '/accounts/%s/extensions',
  'Applications': '/accounts/%s/applications',
  'CallLogs': '/accounts/%s/call-logs',
  'Devices': '/accounts/%s/devices',
  'Listeners': '/accounts/%s/listeners',
  'ExpressServiceCodes': '/accounts/%s/express-service-codes',
  'CallerIds': '/accounts/%s/extensions/%s/caller-ids',
  'Contacts': '/accounts/%s/extensions/%s/contacts',
  'Groups': '/accounts/%s/extensions/%s/contact-groups',
  'Media': '/accounts/%s/media',
  'Menus': '/accounts/%s/menus',
  'PhoneNumbers': '/accounts/%s/phone-numbers',
  'Queues': '/accounts/%s/queues',
  'Routes': '/accounts/%s/routes',
  'Schedules': '/accounts/%s/schedules',
  'Sms': '/accounts/%s/sms',
  'Subaccounts': '/accounts/%s/subaccounts',
  'Trunks': '/accounts/%s/trunks'
};
